### ISSUE TITLE
Coordinators Update in Coordinators Team Page

### ISSUE THREAD

**Issue by Hardik-Mittal** [MNNIT-Robotics-Club-Official/Robotics_Club_Website#125]
Some coordinators needed to be removed from [this page](https://roboticsclub.mnnit.ac.in/coordinator/).
Coordinators to be removed : 
1. Ankur Pratap Singh
2. Mhd Sahil
3. Karim Mohammad
4. Harsh Kumar
5. Anshika Jain
And comment out Mehul Singhal (do not delete the card of Mehul Singhal from the code, only comment it out).

Also, Add/Update senior coordinators details from [this link](https://drive.google.com/file/d/1KWSsKbo7-a07knRZIZKZ9iZWLcFFu1up/view?usp=sharing). And delete unused image files from the coordinator page.

**Comment by pramod74** [comment]
Hi @Hardik-Mittal,

I would like to fix this issue. Can you please assign it to me?

Thanks,
Pramod

**Comment by Hardik-Mittal** [comment]
Hi @pramod74 ,

Sorry, this issue is only for club members. So, I can't assign it to you.

**Comment by pramod74** [comment]
No problem, Hardik. Thanks for the update.

**Comment by agg-geek** [comment]
I am Abhinav from Robotics club. I will take up this issue.

Regards,
Abhinav

**Comment by Hardik-Mittal** [comment]
Okay @agg-geek, I have assigned this issue to you. You can start working on it.

**Comment by Lalit1471** [comment]
I would like to fix this issue. Can you please assign it to me?

**Comment by Hardik-Mittal** [comment]
@Lalit1471 I have assigned this issue to you.
