### ISSUE TITLE
Notice Board - Structured Content

### ISSUE THREAD

**Issue by Hardik-Mittal** [MNNIT-Robotics-Club-Official/Robotics_Club_Website#126]
Need to provide formatting option in "Create Notice". So, it will appear the same way we entered and formatted it. You can take the reference from "Create Project".

E.g.,
If we create a notice in the following manner, it should be visible in the same structured and formatted in the [Notice Board Page](https://roboticsclub.mnnit.ac.in/news/) to others:-
Hello Freshers,
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra libero vestibulum, semper nulla quis, hendrerit nibh. Suspendisse tristique tincidunt mauris.

1. Lorem ipsum1
2. Lorem ipsum2
3. Lorem ipsum3

Regards, 
Robotics

**Comment by Lalit1471** [comment]
@Hardik-Mittal may I take this issue?

**Comment by Lalit1471** [comment]
@Hardik-Mittal 
I would like to fix this issue. Can you please assign it to me?

**Comment by DuP-491** [comment]
@Lalit1471  the issue has been assigned to you now
