### ISSUE TITLE
SignUp Page - Password Field Correction

### ISSUE THREAD

**Issue by Hardik-Mittal** [MNNIT-Robotics-Club-Official/Robotics_Club_Website#131]
In mobile view, **Password** field is not accessible by the user on [SignUp Page](https://roboticsclub.mnnit.ac.in/user/register/).

![SignUp](https://user-images.githubusercontent.com/65127242/150566329-d308481f-8b2e-42a2-a8ec-b257c1714949.jpeg)

Make the field accessible by the user.

**Comment by akash-kd** [comment]
i will take up this issue sir

**Comment by Hardik-Mittal** [comment]
I have assigned this issue to you.
