### ISSUE TITLE
Remove Demote Option

### ISSUE THREAD

**Issue by Hardik-Mittal** [MNNIT-Robotics-Club-Official/Robotics_Club_Website#136]
Remove **Demote** option from the Members  and  **Demote Button** from the heads for current user on the **Manage User Permissions** page.

**Comment by Lalit1471** [comment]
Sir, I would like to take up this issue.

**Comment by ShivamKumar-mnnit** [comment]
I would like to take this issue

**Comment by prackode** [comment]
@ShivamKumar-mnnit you may work on some other issue. This issue was already resolved.
